repos:
  - repo: local

    hooks:
      - id: isort
        name: sort imports
        entry: poetry run isort
        types:
          - python
        language: system
        stages:
          - commit

      - id: black
        name: reformat code with black
        entry: poetry run black
        types:
          - python
        language: system
        stages:
          - commit

      - id: flake8
        name: lint code with flake8
        entry: poetry run flake8
        types:
          - python
        language: system
        stages:
          - commit

      - id: mypy
        name: test types
        entry: poetry run mypy
        types:
          - python
        language: system
        stages:
          - commit